gammapy/gammapy-v1.0-paper

.pre-commit-config.yaml, environment.yml, src/text/0-abstract.tex, src/text/1-introduction.tex, src/text/2-package.tex, src/text/3-applications.tex, src/text/3.1-cta.tex, src/text/3.2-hess.tex, src/text/3.3-fermi.tex, src/text/4-project.tex, src/text/5-summary-outlook.tex
This pull requests add pre commit hooks to check for the consistency of the latex file. For now I just added some standard ones from https://github.com/jonasbb/pre-commit-latex-hooks.
=> Add pre commit hooks

.latex-indent-config.yaml, .pre-commit-config.yaml, latexindent.py, src/text/0-abstract.tex, src/text/2-package.tex, src/text/5-summary-outlook.tex
This pull request adds a pre commit hook for `latex indent.pl` to apply a uniform formatting of the `.tex` files.
=> Add latexindent pre commit hook

.pre-commit-config.yaml, README.md, src/text/2-package.tex
This PR improves the `README.md` by adding some more details on scope and how to get started with the paper writing. It also adds a spellcheck pre-commit hook.
=> Improve readme

src/code-examples/minted.py, src/ms.tex, src/text/0-authors.tex
This PR updates the author list with some more affiliations.
=> Update author list

scripts/latexindent.py, src/text/2-package-subsections/analysis.tex, src/text/2-package-subsections/astro.tex, src/text/2-package-subsections/catalog.tex, src/text/2-package-subsections/data.tex, src/text/2-package-subsections/datasets.tex, src/text/2-package-subsections/estimators.tex, src/text/2-package-subsections/irf.tex, src/text/2-package-subsections/makers.tex, src/text/2-package-subsections/maps.tex, src/text/2-package-subsections/modeling.tex, src/text/2-package-subsections/stats.tex, src/text/2-package-subsections/utils.tex, src/text/2-package-subsections/visualisation.tex, src/text/2-package.tex, src/text/3-applications.tex
This PR split the sub-sections in `2-package` into multiple files to allow for parallel writing of those sections.
=> Split package text into multiple files

src/text/2-package-subsections/datasets.tex
The text is, by no means, the final one. Wanted to add some rough content to create a first PR and test
=> First text in dataset subpackage

src/text/2-package-subsections/datasets.tex, src/text/2-package.tex
This follows issue #9 and corrects a problem that appeared in CI.
=> Changed subsection order and add label in datasets

src/.gitignore, src/code-examples/snippets/gp_estimators.py, src/text/2-package-subsections/datasets.tex, src/text/2-package-subsections/estimators.tex, src/text/2-package-subsections/makers.tex
This PR adds and estimators code example and reformats the other.
=> Reformat and add estimators code examples

src/data/fermi-ts-map/make.py
=> Add make.py script for Fermi data

Snakefile, scripts/download.py, showyourwork.yml, src/data/lightcurve/make.py, src/figures/hess_lightcurve_pks.py, src/figures/lightcurve.py, src/text/3.2-hess.tex
Adding a plot for PKS2155 lightcurve as discussed. 
I can't get src/data/lightcurve/make.py to compile automatically, @adonath any suggestions what I should add?
=> Add lightcurve plot

src/code-examples/snippets/gp_maps.py, src/text/2-package-subsections/maps.tex
Added and expanded the existing snippet
Added paragraph on the MapAxis types
Maybe a plot would be good? else I think the structure is there
=> A bit more work on the map section

.github/workflows/showyourwork.yml, .gitignore, .gitmodules, Makefile, Snakefile, environment.yml, showyourwork.yml, src/.gitignore, src/figures/codestats.py, src/text/4-project.tex
This PR adds the `src/figure/codestats.py` file which creates the piecharts for the coding languages and extension files present in Gammapy, as well as a LaTex file providing a table with the number statistics for the different types of languages used in the Gammapy project.
=> Add codestats figures and table

.gitignore, src/bib.bib, src/text/2-package-subsections/modeling.tex
Add bibliography entries for fit backend and models packages.
Add subsections for Models and Fit.
Content is based on the text in the doc pages and notebooks.
=> Add modeling description

src/bib.bib, src/code-examples/snippets/gp_catalogs.py, src/text/2-package-subsections/catalog.tex
I can't compile locally - error in codestats in run_cloc
```
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cloc'
[Tue Mar  1 16:51:45 2022]
Error in rule codestats:
jobid: 15
output: src/tables/generated/codestats.tex
conda-env: /Users/ASinha/Gammapy-dev/gammapy-v1.0-paper/.snakemake/conda/f04011d7d0581acf890fe3c238008708
shell:
cd src/figures/ && python codestats.py
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```
any suggestions @Bultako ?
=> Write catalog subsection

src/text/3-applications-subsections/1D-analysis.tex
This PR adds the technical description for the 1D analysis example.
=> Add some draft text for the 1D analysis example

src/bib.bib, src/code-examples/snippets/gp_stats.py, src/text/2-package-subsections/stats.tex
This adds the gammapy.stats subsection. A small code snippet shows how to use `CountsStatistics` classes.
=> Add stats subsection

src/text/2-package-subsections/analysis.tex
Add a first draft of text for the analysis sub-module.
=> Analysis submodule text

Snakefile, showyourwork.yml, src/bib.bib, src/data/cube-analysis/make.py, src/figures/cube_analysis.py, src/text/3-applications-subsections/3D-analysis.tex
I've started the draft of the 3D analysis section. I would say the bulk of the text is mostly there, however, I haven't included any figures yet, mainly because I think there are several options and I wanted some feedback before I put the work into getting the figures into the paper. 
As mentioned in the text, I simulated 3 sources with different morphology and spectra. Then I fitted models to the simulated dataset and recovered the simulated parameters pretty closely. 
My current proposal for plots to add (perhaps as a 3 panel figure, or 2 panel with the maps + a different figure for the histogram) is:
* Significance map 
* Residual map after fitting
* Contribution to a region around the point source for each model
The colorbars would have labels and I would think the choice of colors …
=> Draft of 3D analysis section

src/text/2-package-subsections/maps.tex, src/text/3-applications-subsections/3D-analysis.tex
I went over the Maps and 3D section and fixed some small issues, like references to other figures or sections and some language.
=> Small changes to the Maps and 3D analysis section

src/text/2-package.tex
This is a draft for the analysis workflow.
We might decide on:
- how detailed low level analysis. Do we need a figure to show the whole data flow?
- Do we discuss here Npred and IRF factorization? Do we simply use a reference?
I have also added references to the relevant sub packages when presenting the workflow.
=> First draft for workflow section

src/bib.bib, src/text/5-summary-outlook.tex
=> Add draft for summary and conclusions

src/code-examples/snippets/gp_data.py, src/code-examples/snippets/gp_estimators.py, src/code-examples/snippets/gp_makers.py, src/code-examples/snippets/gp_maps.py, src/code-examples/snippets/gp_models.py, src/code-examples/snippets/gp_stats.py
This PR cleans up code snippets so that there are no fails
=> Cleanup code snippets

src/bib.bib, src/text/1-introduction.tex
This is first contribution to the introduction section. It still needs to be improved in particular in the general description of the Gammapy context and the main steps since the creation of the project.
=> Write the introduction section

src/text/0-shortcuts.tex, src/text/2-package-subsections/visualisation.tex
=> Write visualisation section

src/data/multi-instrument/make.py, src/figures/multi_instrument_analysis.py
First of all, I am really sorry for the delay on this.
I added to the multi-instrument example a fit with a `NaimaSpectralModel`.
The model considers inverse Compton scattering by a log-parabolic electron distribution. The photon targets considered, following the prescription of [this example in the `naima` docs](https://naima.readthedocs.io/en/latest/examples.html#crab-nebula-ssc-model), are:
- synchrotron radiation by the same electrons,
- far and near infrared radiation (see the naima example for the temperatures and densities);
- the CMB.
In the `naima` example, a (smooth) broken power law with a cutoff is used for the particles energy distribution. I found it difficult to fit the gamma-ray data with it, so I adopted a simpler log-parabolic shape. This is the result:
I directly run …
=> Added a fit with a physical model to the multi-instrument fit example

Snakefile, environment.yml, scripts/download.py, showyourwork.yml
=> Update to v1.0 data and fix PDF file

src/ms-review.tex
This is a proposal for a more structured section 2.
I have added a rapid reminder about the background model and give a simplified formula for the total number of predicted counts.
=> Improve Section 2

src/ms-review.tex
Here goes my review before circulation to the whole Gammapy project.
@adonath suggested to make only grammatical changes.
But I think there is still some polishing that can be done; also I noticed this is the first time I read the paper as a whole. 
So I have incorporated further comments as latex comments in `ms-review.tex`.  So that they can be picked up at later review stages.
I only changed 2 sentences slightly and I comment below the reason why, the rest is really small typos / fixes.
=> Author review before publication

src/bib.bib, src/ms-review.tex
Completes the round of review started in #84.
Cheers.
=> Second round review before circulation to collaboration

src/figures/data_flow.py
Signed-off-by: Bruno Khélifi <khelifi@in2p3.fr>
=> Update the figure 2

src/ms-review.tex
Signed-off-by: Bruno Khélifi <khelifi@in2p3.fr>
=> Update the author list

src/ms-review.tex
Reduction of the abstract length to 290 words. This leaves some margin for comments as the limit is 300 words.
Signed-off-by: Bruno Khélifi <khelifi@in2p3.fr>
=> Reduce the abstract length

src/figures/codestats.py
This at least provides a less confusing error than the one in #92
=> Add check to subprocess calls

src/ms-review.tex
Minor rewording in the abstract.
* English sentence structure
* missing "support"
* Fix for "softwares" (no plural in English)
=> Rewording in abstract

src/ms-review.tex
This PR implements the comments we received from Jose Luis.    
They were all related to grammar, no major comment on the manuscript was given, except to run a spell check.
=> Implemented comments from Jose Luis Contreras' review

.github/workflows/showyourwork.yml, src/data/codestats.csv, src/figures/codestats.py, src/ms-review.tex
Update code stats plot and remove the dependency on `cloc` by committing the code stats table.
=> Update codestats plot

src/bib.bib, src/ms-review.tex
Few comments on figures are remaining:
Why is this light grey vs. regular grey (others)? (QR: for data reduction and modelling & fitting)
Maybe you could look once more to improve this. However also not a big deal.
=> Implement comments from Matthias Fuessling

src/ms-review.tex
=> Update of the author list

src/ms-review.tex
This PR addresses most of the comments listed in #119.
=> Address comments by A.Siemiginowska

src/code-examples/snippets/gp_estimators.py, src/figures/code_example_gp_estimators.py, src/figures/code_example_gp_makers.py, src/figures/cta_galactic_center.py, src/figures/data_flow.py, src/figures/hess_lightcurve_pks.py, src/figures/irfs.py, src/ms-review.tex
=> Address remaining figure comments

src/bib.bib, src/ms-review.tex
Following the discussion in the issue #102, I make a proposal of small improvement, saying that 1) one will improve our algorithms and 2) one will improve our interfaces to external lib...
=> Time-based analysis in the Outlook section

src/bib.bib, src/ms-review.tex
I've added a reference to the core-science of the ASTRI mini-array in the outlook section.
=> Add reference to ASTRI paper

src/ms-review.tex
This PR addressed #111, by adding some more context to the introduction and also specifying the energy range for the Fermi-LAT.
=> Add some more context to the introduction

src/ms-review.tex
This PR proposes some changes suggested in #115 .
=> Corrections after issue 115

src/bib.bib, src/ms-review.tex
=> Last BK comments

Snakefile, scripts/download.py, showyourwork.yml, src/bib.bib, src/code-examples/snippets/gp_models.py, src/data/cta-galactic-center/make.py, src/data/cube-analysis/make.py, src/data/lightcurve/make.py, src/data/multi-instrument/make.py, src/figures/big_picture.py, src/figures/data_flow.py, src/ms-review.tex
This Pull requests addresses comments raised by the referee of A&A. We have and internal document with the answers to the referee. I will ask for permission to make the specific comments / review public later. Please take a look at the internal document and check whether the PR addresses the comments accordingly.
The PDF is available here https://github.com/adonath/gammapy-v1.0-paper/raw/address_referee_comments-pdf/ms.pdf for download.
=> Address referee comments

src/ms-review.tex
First this PR moves people that directly contributed text during the review phase to the "paper author" section. Second this PR removes some repetition of the description of the data reduction found after #145.
=> Update author list and remove repetitions of data reduction description

src/bib.bib, src/ms-review.tex
This PR prepares the tex files for submission to the language editor and arXiv upload.
=> Prepare tex files

src/ms-review.tex
This PR contains language edits proposed by the language editor. No review necessary.
=> Language edits
